import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner"
import Card from "../components/card";

export default function Home() {
  const handleOnBannerBtnClick = () => {
      console.log("hi banner button")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>shop discover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Banner
              buttonText="View stores nearby"
              handleOnClick={handleOnBannerBtnClick}
          />
          <div className={styles.heroImage}>
              <Image src="" width={700} height={400}/>
          </div>
          <Card
              name='Dark Horse Coffee'
              imgUrl="https://lottiefiles.com/91070-hot-smiling-coffee-good-morning"
              href="/coffee-store/darkhorse-coffee"
          />
      </main>
    </div>
  )
}
